services:
  application:
    build: ./application
    ports:
     - "80:80"
     - "443:443"
    environment:
      APP_ENV: production
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: books
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: "mysql -uroot -p books -e 'select 1'"
      interval: 1s
      retries: 120
    volumes:
     - books-database:/var/lib/mysql
  database-loader:
    build: ./database-loader
    depends_on:
      mysql :
        condition: service_healthy
volumes:
  books-database: