# This workflow deploys changes made to this branch to the production server

name: Deploy changes

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Copy private SSH key
      env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
          mkdir -p ~/.ssh/
          echo "${SSH_KEY}" > ~/.ssh/library
          chmod 600 ~/.ssh/library

    - name: Configure client SSH
      env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
      run: |
          cat >>~/.ssh/config <<END
          Host production
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/library
              StrictHostKeyChecking no
          END

    - name: Fetch changes on host and rebuild
      run: |
          ssh production 'cd /libraryBackend && git fetch && docker compose up --build -d'