# This workflow deploys changes made to this branch to the production server

name: Deploy changes

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Copy private SSH key
      env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
          mkdir -p ~/.ssh/
          echo "${SSH_KEY}" > ~/.ssh/library
          chmod 600 ~/.ssh/library
          eval `ssh-agent -s`
          ssh-add ~/.ssh/library
        
    - name: Fetch changes on host and rebuild
      env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      run: |
          ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} 'cd /libraryBackend && git fetch && docker compose up --build'